import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/navbar'
import styles from '/styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>R6 Help - Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        Header here
      </header>
      {Navbar}

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/maps/bank">Mambo #5</a>
        </h1>

        <p className={styles.description}>
          Some{' '}
          <code className={styles.code}>code</code>
        </p>

        <div className={styles.grid}>
          <a href="/maps" className={styles.card}>
            <h2>Maps &rarr;</h2>
            <p>Ranked and Casual map pool (excluding Barlett)</p>
          </a>

          <a href="/operators" className={styles.card}>
            <h2>Operators &rarr;</h2>
            <p>Operators utility, usage and fun facts</p>
          </a>

          <a href="#" className={styles.card}>
            <h2 >Ideas from you &rarr;</h2>
            <p>Map & strat ideas/propositions from you </p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Extra &rarr;</h2>
            <p>Extra &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; Extra &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Me{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
