import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from 'components/Navbar'
import Center from 'components/Center'
import styles from '/styles/Home.module.css'
// import Home from 'pages/home'
import Maps from 'pages/maps'
import Bank1 from 'pages/maps/bank1'
import { SetStateAction, useState } from 'react'

const Index: NextPage = () => {

  const [first, setFirst] = useState<any>(); // use it to show a different Navbar when clicking on Maps (maybe show all maps name..?)

  const Home = () => {
    return (
      <div className={styles.container}>
        <div className={styles.main}>
          <h1 className={styles.title}>
            Welcome to
            <Link href={"/maps/bank"}>
              <a> R6 Help</a>
            </Link>
          </h1>

          <p className={styles.description}>
            Some <code className={styles.code}>code</code>
          </p>

          <div className={styles.grid}>
            <a className={styles.card} onClick={() => setRendered(<Maps setRender={setRendered} />)}>
              <h2>Maps &rarr;</h2>
              <p>Ranked and Casual map pool (excluding Barlett)</p>
            </a>

            <Link href={"/operators"}>
              <a className={styles.card}>
                <h2>Operators &rarr;</h2>
                <p>Operators utility, usage and fun facts</p>
              </a>
            </Link>

            <Link href={"/"}>
              <a className={styles.card}>
                <h2>Ideas from you &rarr;</h2>
                <p>Map & strat ideas/propositions from you </p>
              </a>
            </Link>

            <Link href={"/"}>
              <a className={styles.card}>
                <h2>Extra &rarr;</h2>
                <p>
                  Extra &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr;
                  &rarr; Extra &rarr; &rarr; &rarr; &rarr; &rarr; &rarr; &rarr;
                  &rarr; &rarr;{" "}
                </p>
              </a>
            </Link>
          </div>
        </div>

        {/* <footer className={styles.footer}>
                  <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                  >
                    Powered by Me{' '}
                    <span className={styles.logo}>
                      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                  </a>
                </footer> */}
      </div>
    );
  };

  // setRendered(<Home here = {setRendered}/>);
  // function renderer(renderThis: SetStateAction<JSX.Element>)
  // {
  //   setRendered(renderThis);
  // }
  const [rendered, setRendered] = useState<any>(<Home />);

  return (
    <div className='bg-black h-screen overflow-hidden'>
      <Head>
        <title>R6 Help - Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex'>
        <Navbar setRender={setRendered} home={Home} maps={first} />
        {/* <Center/> */}
        <div className='h-screen w-screen overflow-auto'>
          {rendered}
        </div>
      </main>
    </div>
  )
}

export default Index
