import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Navbar from 'components/Navbar'
import styles from '/styles/Maps.module.css'

const allMaps = [
  "Bank",
  "Border",
  "Chalet",
  "Club House",
  "Coastline",
  "Consulate",
  "Favela",
  "Fortress",
  "Hereford Base",
  "House",
  "Kafe Dostoevsky",
  "Kanal",
  "Oregon",
  "Outback",
  "Presidential Plane",
  "Skyscraper",
  "Theme Park",
  "Tower",
  "Villa",
  "Yacht"];

const Maps: NextPage = () => {
  const cx = (...classNames: any[]) => classNames.join(' ');
  return (
    <div className='bg-black h-screen overflow-hidden'>

      <Head>
        <title>R6 Help - Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <header className={styles.header}>
        Header here
      </header> */}
      <main className='flex'>
        <Navbar />
        <div className='overflow-auto h-screen w-screen bg-black'>
          <div className={styles.container}>
            <div className={styles.main}>
              <h1>
                Maps
              </h1>
              <div className={styles.grid}>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.bank)}>
                    Bank
                  </a>
                </Link>
                <Link href={"/maps/bank1"}>
                  <a className={cx(styles.card, styles.border)}>
                    Border
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.chalet)}>
                    Chalet
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.clubhouse)}>
                    Club House
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.coastline)}>
                    Coastline
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.consulate)}>
                    Consulate
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.favela)}>
                    Favela
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.fortress)}>
                    Fortress
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.hereford)}>
                    Hereford Base
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.house)}>
                    House
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.kafe)}>
                    Kafe Dostoyevsky
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.kanal)}>
                    Kanal
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.oregon)}>
                    Oregon
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.outback)}>
                    Outback
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.plane)}>
                    Presidential Plane
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.skyscraper)}>
                    Skyscraper
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.themepark)}>
                    Theme Park
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.tower)}>
                    Tower
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.villa)}>
                    Villa
                  </a>
                </Link>
                <Link href={"/maps/bank"}>
                  <a className={cx(styles.card, styles.yacht)}>
                    Yacht
                  </a>
                </Link>
              </div>
            </div>
            
          </div>
        </div>
      </main>
    </div>
  )
}

export default Maps
