/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '/styles/Map.module.css'
import React, { useState, useEffect } from 'react';
import Draggable from 'react-draggable';
import Operators from '../operators'


const Bank: NextPage = () => {
        const nodeRef = React.useRef(null);
    // Definimos los estados
    const [name, setName] = useState(String)
    const [count, setCount] = useState(Number)
    const [visibility, setVisibility] = useState(false)

    // Los estados definidos se pueden usar dentro de otras funciones
    function getName(){
        console.log(name)
    }

    // Funciona como un componentDidMount y componentDidUpdate al mismo tiempo.
    // Es decir, se ejecutara inmediatamente cargado el sitio sin la necesidad de un boton
    // Y se ira actualizando al mismo tiempo que vaya cambiando su valor
    useEffect(() => {
        // document.title = `${count} Clicks`
        console.log(`Number of clicks : ${count}`)
    })
  return (
    <div className={styles.container}>
        <Head>
            <title>R6 Help - Index</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <header className={styles.header}>
            Header here
        </header>

        <main className={styles.main}>
            <div className={styles.flexOps}>
                <Operators/>
            </div>
            <div>
                <p>Input Name: <input type="text" onChange={e => setName(e.target.value)} /></p>
                <p>Name: {name}</p>
                <button onClick={getName}>console.log(name)</button>
                <br/>
                <button onClick={() => setVisibility(!visibility) }>Click Me {visibility}</button>
                { visibility ? <Operators /> : null }
            </div>
            <div id='utilities' className={styles.flexOps}>                
                <Draggable nodeRef={nodeRef}>
                    <img ref={nodeRef} src='/utilities/green-dot1.png' alt='Green Dot' width={25} height={25} title={'Crouch'}>
                    </img>
                </Draggable>
                 <Draggable nodeRef={nodeRef}>
                    <img ref={nodeRef} src='/utilities/green-dot2.png' alt='Green Dot' width={25} height={25} title={'Crouch'}>
                    </img>
                </Draggable>
                <Draggable nodeRef={nodeRef}>
                    <img ref={nodeRef} src='/utilities/green-dot3.png' alt='Green Dot' width={25} height={25} title={'Crouch'}>
                    </img>
                </Draggable>
                <Draggable nodeRef={nodeRef}>
                    <img ref={nodeRef} src='/utilities/green-dot4.png' alt='Green Dot' width={25} height={25} title={'Crouch'}>
                    </img>
                </Draggable>
                <Draggable nodeRef={nodeRef}>
                    <img ref={nodeRef} src='/utilities/line.png' alt='Green Dot' width={25} height={25} title={'Crouch'}>
                    </img>
                </Draggable>
            </div>
            <img src='/maps/bank/r6-maps-bank-blueprint-1.jpg' alt='Bank 2nd Floor  ' height={'85%'} width={'85%'}>
            </img>
            <img src='/maps/bank/r6-maps-bank-blueprint-2.jpg' alt='Bank 2nd Floor  ' height={'85%'} width={'85%'}>
            </img>
            <img src='/maps/bank/r6-maps-bank-blueprint-3.jpg' alt='Bank 2nd Floor  ' height={'85%'} width={'85%'}>
            </img>
            <img src='/maps/bank/r6-maps-bank-blueprint-4.jpg' alt='Bank 2nd Floor  ' height={'85%'} width={'85%'}>
            </img>

        </main>

        <footer className={styles.footer}>
            <a href="#" target="_blank" rel="noopener noreferrer">
                Powered by Me{' '}
                <span className={styles.logo}>
                    <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                </span>
            </a>
        </footer>
    </div>
  )
}

export default Bank
